# Generated by Django 4.2.3 on 2023-09-18 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', flags=django.db.models.constraints.UniqueConstraint, message='Name must be unique and case-sensitive.')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', flags=django.db.models.constraints.UniqueConstraint, message='Name must be unique and case-sensitive.')]),
        ),
    ]
