# Generated by Django 4.2.5 on 2023-09-14 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
