# Generated by Django 4.2.5 on 2023-10-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
    ]
