from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import LoginForm,MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm


urlpatterns = [
    path('', views.ProductView.as_view(),name='home'),
    path('product-detail/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('submit_product_review/<int:product_id>/', views.submit_product_review, name='submit_product_review'),
    path('product-listing/<str:category>/',views.product_listing,name='product_listing'),
    path('profile/add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('profile/wishlist/',views.wishlist, name='wishlist'),
    path('profile/remove_from_wishlist/<int:product_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('toggle-wishlist/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    # path('buy/', views.buy_now, name='buy-now'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('edit-profile/', views.edit_user_profile, name='edit_profile'),
    path('address/', views.address, name='address'),
    path('address/edit-address/<int:address_id>/',views.edit_address, name = 'edit_address'),
    path('address/delete/<int:address_id>/', views.delete_address, name='delete_address'),
    path('user-orders/', views.user_orders, name='user_orders'),
    path('order/<int:order_id>/', views.order_details, name='order_details'),
    path('order/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('mobile/', views.mobile, name='mobile'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name= 'app/login.html',authentication_form=LoginForm), name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='login'),name= 'logout'),
    path('resend-otp/', views.OTPVerificationView.as_view(), name='resend_otp'),
    path('password-change/', views.password_change_view, name='passwordchange'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='app/passwordchangedone.html'), name='password_change_done'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='app/password_reset.html', form_class=MyPasswordResetForm),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html', form_class=MySetPasswordForm),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'),name='password_reset_complete'),
    path('registration/', views.CustomerRegistrationView.as_view(), name='customer_registration'),
    path('registration/verify-otp/', views.OTPVerificationView.as_view(), name='verify_otp'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('admin-home', views.admin_home, name='admin_home'),
    path('registration_complete/', views.registration_complete, name='registration_complete'),
    path('max_attempts_exceeded/', views.max_attempts_exceeded, name='max_attempts_exceeded'),
    path('admin-home/user-list/', views.user_list, name='user_list'),
    path('admin-home/admin-list/', views.is_admin_list, name='is_admin_list'),
    path('admin-home/products/', views.ProductListView.as_view(), name='product_list'),
    path('admin-home/add-product/', views.add_product, name='add_product'),
    path('admin-home/delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('admin-home/add-product-image/<int:product_id>/', views.add_product_images, name='add_product_image'),
    path('admin-home/edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('admin-home/delete-product-image/<int:image_id>/', views.delete_product_image, name='delete_product_image'),
    path('admin-home/categories/', views.category_list_and_add, name='category_list_and_add'),
    path('admin-home/categories/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('admin-home/edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('admin-home/brands/', views.brand_list_and_add, name='brand_list_and_add'),
    path('admin-home/brands/delete/<int:brand_id>/', views.delete_brand, name='delete_brand'),
    path('admin-home/edit-brand/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('admin-home/toggle-user-status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('admin-home/toggle-user-credential/<int:user_id>/', views.toggle_user_credential, name='toggle_user_credential'),
    path('admin-home/orders/', views.admin_orders, name='admin_orders'),
    path('admin-home/edit-order-status/<int:order_id>/', views.admin_edit_order_status, name='admin_edit_order_status'),
    path('profile/cart/', views.cart, name='cart'),
    path('profile/add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('profile/cart/delete/<int:item_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('profile/buy-now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('plus-cart/',views.plus_cart, name='plus_cart'),
    path('minus-cart/',views.minus_cart, name='minus_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('order-placed',views.order_placed, name='order_placed'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('generate-invoice/<int:order_id>/',views.generate_pdf, name='generate_pdf'),
    path('admin-home/create-product-offer/', views.create_product_offer, name='create_product_offer'),
    path('admin-home/product-offer-list/', views.product_offer_list, name='product_offer_list'),
    path('admin-home/create-category-offer/', views.create_category_offer, name='create_category_offer'),
    path('admin-home/category-offer-list/', views.category_offer_list, name='category_offer_list'),
    path('admin-home/create-referral-offer/', views.create_referral_offer, name='create_referral_offer'),
    path('admin-home/referral-offer-list/', views.referral_offer_list, name='referral_offer_list'),
         ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
